import type { Metadata } from "next";
import { site, DISCLOSURE } from "@/lib/config";
export const metadata: Metadata = { title: "Non-affiliation disclosure" };
export default function Page() {
  return (
    <div className="prose-basic mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-3xl font-bold">Non-affiliation disclosure</h1>
      <p className="mt-4">{DISCLOSURE}</p>
      <h2>What this means for you</h2>
      <ul>
        <li>You can complete the arrival card yourself, free of charge, at <a href={site.officialPortal} rel="noopener nofollow">{site.officialPortal}</a>. Our <a href="/guide">free guide</a> explains every step.</li>
        <li>Our fee is for a service: guided data collection, manual verification, submission on your behalf, delivery and support.</li>
        <li>We do not issue visas, arrival cards or any government document. The QR code you receive is generated by the Indonesian government system.</li>
        <li>We do not use government logos, emblems or names in our branding, and we are not endorsed by any Indonesian authority.</li>
      </ul>
      <h2>Operator</h2>
      <p>{site.company}, {site.address}, {site.companyReg}. Contact: <a href={`mailto:${site.supportEmail}`}>{site.supportEmail}</a>.</p>
    </div>
  );
}
